# set default task and training config
defaults:
  - task: genesis_default
  - agent: afrl
  - _self_

# Logging
hydra:
  run:
    dir: logs/${agent.name}/${task.backend}/${task.env.env_name}/${now:%Y-%m-%d_%H-%M-%S}

# general
seed: 0
device: cuda

num_envs: ${agent.num_envs}
